#!/bin/zsh

#!/bin/bash

#          ╭──────────────────────────────────────────────────────────╮
#          │                    DAILY CONTAINER  BLOCK                │
#          ╰──────────────────────────────────────────────────────────╯

# ── DOCK DEFAULTS ────────────────────────────────────────────────────
ICON_FONT="Font Awesome 6 Free:Solid:15"

# Function to generate app configuration


# Get all spaces
SPACES=($(yabai -m query --spaces index | jq -r '.[].index'))


for SID in "${SPACES[@]}"; do
  $LEFT_BAR --add space space.$SID left   \
    --set space.$SID "${spaces[@]}"        \
    script="$PLUGIN_DIR/app_space.sh $SID" \
    associated_space=$SID                  \
    icon=$SID                              \
    --subscribe space.$SID mouse.clicked front_app_switched space_change update_yabai_icon space_windows_change
done
