#!/bin/bash

#          ╭──────────────────────────────────────────────────────────╮
#          │              GENERAL CONTAINER BLOCK                     │
#          ╰──────────────────────────────────────────────────────────╯

# ── DEFAULTS ──────────────────────────────────────────────────────────
BLOCK_POSITION="right"

common=(
	label.color="$DULL_LABEL_COLOR"
	icon.font="$FONT_AWESOME"
	icon.padding_left=5
	icon.color="$ICON_COLOR"
	label.font="$FIRA_CODE_FONT"

)

# ── VOLUME SETTINGS ───────────────────────────────────────────────────
volume=(
	script="$VOLUME_SCRIPT"
	icon=
	update_freq=120

)

# ── BATTERY SETTINGS ──────────────────────────────────────────────────
battery=(
	script="$BATTERY_SCRIPT"
	update_freq=120
	icon=
	click_script="$BATTERY_SCRIPT"
)

# ── WIFI SETTINGS ──────────────────────────────────────────────────────
wifi=(
	script="$WIFI_SCRIPT"
	icon=􀙇
	update_freq=120
)

# ── $LEFT_BAR CONFIGURATION ─────────────────────────────────────────
$LEFT_BAR \
	--add item wifi "$BLOCK_POSITION" \
	--subscribe wifi wifi_change \
	--set wifi "${wifi[@]}" "${common[@]}"

$LEFT_BAR \
	--add item battery "$BLOCK_POSITION" \
	--subscribe battery system_woke power_source_change \
	--set battery "${battery[@]}" "${common[@]}"

$LEFT_BAR \
	--add item volume_icon "$BLOCK_POSITION" \
	--subscribe volume_icon volume_change \
	--set volume_icon "${volume[@]}" "${common[@]}" padding_left=22
