#!/bin/bash

#          ╭──────────────────────────────────────────────────────────╮
#          │              GENERAL CONTAINER BLOCK                     │
#          ╰──────────────────────────────────────────────────────────╯

# ── DEFAULTS ──────────────────────────────────────────────────────────
BLOCK_POSITION="right"

common=(
	label.color="$DULL_LABEL_COLOR"
	icon.font="$FONT_AWESOME"
	icon.padding_left=5
	icon.color="$ICON_COLOR"
	label.font="$FIRA_CODE_FONT"

)

# ── VOLUME SETTINGS ───────────────────────────────────────────────────
volume=(
	script="$VOLUME_SCRIPT"
	icon=
	update_freq=50

)

# ── BATTERY SETTINGS ──────────────────────────────────────────────────
battery=(
	script="$BATTERY_SCRIPT"
	update_freq=50
	icon=
	click_script="$BATTERY_SCRIPT"
)
OPEN_WIFI_PREFERENCE='open x-apple.systempreferences:com.apple.preference.network?Wi-Fi'
# ── WIFI SETTINGS ──────────────────────────────────────────────────────

wifi=(
	script="$WIFI_SCRIPT"
	icon=􀙇
	click_script="$OPEN_WIFI_PREFERENCE"
	update_freq=50
)

# ── $LEFT_BAR CONFIGURATION ─────────────────────────────────────────
$LEFT_BAR \
	--add item wifi "$BLOCK_POSITION" \
	--set wifi "${wifi[@]}" "${common[@]}" \
	--subscribe wifi wifi_change

$LEFT_BAR \
	--add item battery "$BLOCK_POSITION" \
	--set battery "${battery[@]}" "${common[@]}" \
	--subscribe battery system_woke power_source_change

$LEFT_BAR \
	--add item volume_icon "$BLOCK_POSITION" \
	--set volume_icon "${volume[@]}" "${common[@]}" padding_left=22 \
	--subscribe volume_icon volume_change
