#!/bin/bash

#          ╭──────────────────────────────────────────────────────────╮
#          │                          ICONS                           │
#          ╰──────────────────────────────────────────────────────────╯

# ── DOCK ICONS ────────────────────────────────────────────────────────
export ICON_TERM=󰆍

# ── General Icons ─────────────────────────────────────────────────────
export LOADING=􀖇
export APPLE=􀣺
export PREFERENCES=􀺽
export ACTIVITY=􀒓
export LOCK=􀒳
export BELL=􀋚
export BELL_DOT=􀝗

# ── Git Icons ─────────────────────────────────────────────────────────
export GIT_ISSUE=􀍷
export GIT_DISCUSSION=􀒤
export GIT_PULL_REQUEST=􀙡
export GIT_COMMIT=􀡚
export GIT_INDICATOR=􀂓

# ── Spotify Icons ─────────────────────────────────────────────────────
export SPOTIFY_BACK=􀊎
export SPOTIFY_PLAY_PAUSE=􀊈
export SPOTIFY_NEXT=􀊐
export SPOTIFY_SHUFFLE=􀊝
export SPOTIFY_REPEAT=􀊞

# ── Yabai Icons ───────────────────────────────────────────────────────
export YABAI_STACK=􀏭
export YABAI_FULLSCREEN_ZOOM=􀏜
export YABAI_PARENT_ZOOM=􀥃
export YABAI_FLOAT=􀢌
export YABAI_GRID=􀧍

# ── Battery Icons ─────────────────────────────────────────────────────
export BATTERY_100=􀛨
export BATTERY_75=􀺸
export BATTERY_50=􀺶
export BATTERY_25=􀛩
export BATTERY_0=􀛪
export BATTERY_CHARGING=􀢋

# ── Volume Icons ──────────────────────────────────────────────────────
export VOLUME_100=􀊩
export VOLUME_66=􀊧
export VOLUME_33=􀊥
export VOLUME_10=􀊡
export VOLUME_0=􀊣

# ── WiFi ──────────────────────────────────────────────────────────────
export WIFI_CONNECTED=􀙇
export WIFI_DISCONNECTED=􀙈

# ── svim ──────────────────────────────────────────────────────────────
export MODE_NORMAL=􀂯
export MODE_INSERT=􀂥
export MODE_VISUAL=􀂿
export MODE_CMD=􀂙
export MODE_PENDING=􀈏

#          ╭──────────────────────────────────────────────────────────╮
#          │                      Material Icons                      │
#          ╰──────────────────────────────────────────────────────────╯

export ICON_CMD=󰘳
export ICON_COG=󰒓   # system settings, system information, tinkertool
export ICON_CHART=󱕍 # activity monitor, btop
export ICON_LOCK=󰌾

export ICONS_SPACE=(󰎤 󰎧 󰎪 󰎭 󰎱 󰎳 󰎶)

export ICON_APP=󰣆         # fallback app
export ICON_TERM=󰆍        # fallback terminal app, terminal, warp, iterm2
export ICON_PACKAGE=󰏓     # brew
export ICON_DEV=󰅨         # nvim, neovide, xcode, vscode, intellij
export ICON_FILE=󰉋        # ranger, finder
export ICON_GIT=󰊢         # lazygit
export ICON_LIST=󱃔        # taskwarrior, taskwarrior-tui, reminders, onenote
export ICON_SCREENSAVOR=󱄄 # unimatrix, pipe.sh
export ICON_FINDER=
export ICON_WEATHER=󰖕        # weather
export ICON_VSCODE=         #vscode
export ICON_MAIL=󰇮           # mail, outlook
export ICON_CALC=󰪚           # calculator, numi
export ICON_MAP=󰆋            # maps, find my
export ICON_MICROPHONE=󰍬     # voice memos
export ICON_TEAMS=          # teams
export ICON_CHAT=󰍩           # messages, slack, teams, discord, telegram
export ICON_VIDEOCHAT=󰍫      # facetime, zoom, webex
export ICON_NOTE=󱞎           # notes, textedit, stickies, word, bat
export ICON_CAMERA=󰄀         # photo booth
export ICON_WEB=󰇧            # safari, beam, duckduckgo, arc, edge, chrome, firefox
export ICON_HOMEAUTOMATION=󱉑 # home
export ICON_MUSIC=󰎄          # music, spotify
export ICON_PODCAST=󰦔        # podcasts
export ICON_PLAY=󱉺           # tv, quicktime, vlc
export ICON_BOOK=󰂿           # books
export ICON_BOOKINFO=󱁯       # font book, dictionary
export ICON_PREVIEW=󰋲        # screenshot, preview
export ICON_PASSKEY=󰷡        # 1password
export ICON_DOWNLOAD=󱑢       # progressive downloader, transmission
export ICON_CAST=󱒃           # airflow
export ICON_TABLE=󰓫          # excel
export ICON_PRESENT=󰈩        # powerpoint
export ICON_CLOUD=󰅧          # onedrive
export ICON_PEN=󰏬            # curve
export ICON_REMOTEDESKTOP=󰢹  # remote desktop, vmware, utm
export ICON_HEADSET=        #headset
export ICON_CLOCK=󰥔          # clock, timewarrior, tty-clock
export ICON_CALENDAR=󰃭       # calendar

export ICON_WIFI=󰖩
export ICON_WIFI_OFF=󰖪
export ICON_VPN=󰦝 # vpn, nordvpn

export ICONS_VOLUME=(󰸈 󰕿 󰖀 󰕾)

export ICONS_BATTERY=(󰂎 󰁺 󰁻 󰁼 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹)
export ICONS_BATTERY_CHARGING=(󰢟 󰢜 󰂆 󰂇 󰂈 󰢝 󰂉 󰢞 󰂊 󰂋 󰂅)

export ICON_SWAP=󰁯
export ICON_RAM=󰓅
export ICON_DISK=󰋊 # disk utility
export ICON_CPU=󰘚

export ICON_CODE=
export ICON_DOWNLOADS=
export ICON_DOTS=
export ICON_MINE=
export ICON_WORK=💼
export ICON_VIDA=🫁
export ICON_MORE=
