add_newline = true 

format = """
$directory\
$line_break$character
"""

[directory]
read_only = " "
format = "[$path]($style)[$lock_symbol]($lock_style) "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "italic #45b3e0"

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
